replicaCount: 1

image:
  repository: api-gateway
  tag: latest
  pullPolicy: IfNotPresent


container:
  port: "8080"

service:
  enabled: true
  type: ClusterIP
  port: "8080"

config:
  SERVER_PORT: "8080"
  AUTH_SERVICE_URL: ""
  USER_SERVICE_URL: ""

secrets: 
  JWT_SECRET_KEY: ""