apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullName" . }}-config
data:
  SERVER_PORT: {{ .Values.container.port | quote }}
  AUTH_SERVICE_URL: {{ .Values.global.config.AUTH_SERVICE_URL | default .Values.config.AUTH_SERVICE_URL | quote }}
  USER_SERVICE_URL: {{ .Values.global.config.USER_SERVICE_URL | default .Values.config.USER_SERVICE_URL | quote }}