apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-service.fullName" . }}
  labels: 
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "auth-service.selectorLabels" .| nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: {{ include "auth-service.fullName" . }}-config
            - secretRef:
                name: {{ include "auth-service.fullName" . }}-api-secret
            - secretRef:
                name: {{ include "auth-service.fullName" . }}-db-secret
