apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullName" . }}-db-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.global.secrets.DATABASE_URL | quote }}
  DATABASE_PORT: {{ .Values.global.secrets.DATABASE_PORT | quote }}
  DATABASE_NAME: {{ .Values.global.secrets.DATABASE_NAME | quote }}
  DATABASE_USERNAME: {{ .Values.global.secrets.DATABASE_USERNAME | quote }}
  DATABASE_PASSWORD: {{ .Values.global.secrets.DATABASE_PASSWORD | quote }}
