apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullName" . }}-api-secret
type: Opaque
stringData:
{{- with .Values.global.secrets }}
  JWT_SECRET_KEY: {{ .JWT_SECRET_KEY | quote }}
  JWT_TOKEN_VALIDITY: {{ .JWT_TOKEN_VALIDITY | quote }}
  INTERNAL_API_KEY: {{ .INTERNAL_API_KEY | quote }}
{{- end }}
