apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullName" . }}-db-secret
type: Opaque
stringData:
{{- with .Values.global.secrets }}
  DATABASE_URL: {{ .DATABASE_URL | quote }}
  DATABASE_PORT: {{ .DATABASE_PORT | quote }}
  DATABASE_NAME: {{ .DATABASE_NAME | quote }}
  DATABASE_SCHEMA: {{ $.Values.secrets.DATABASE_SCHEMA | quote }}
  DATABASE_USERNAME: {{ .DATABASE_USERNAME | quote }}
  DATABASE_PASSWORD: {{ .DATABASE_PASSWORD | quote }}
{{- end }}