spring.application.name=api-gateway
server.port=${SERVER_PORT}

# Security
security.jwt.secret-key=${JWT_SECRET_KEY}

# ECS DNS
auth-service-url=${AUTH_SERVICE_URL}
user-service-url=${USER_SERVICE_URL}

# Actuator / health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.server.port=${MANAGEMENT_PORT:${SERVER_PORT}}