apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullName" . }}-config
data:
  SERVER_PORT: {{ .Values.container.port | quote }}
  REGION: {{ .Values.global.config.REGION | default .Values.config.REGION | quote }}
  QUEUE_URL: {{ .Values.global.config.QUEUE_URL | default .Values.config.QUEUE_URL | quote }}