apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullName" . }}-api-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.global.secrets.JWT_SECRET_KEY | quote }}
  JWT_TOKEN_VALIDITY: {{ .Values.global.secrets.JWT_TOKEN_VALIDITY | quote }}
  INTERNAL_API_KEY: {{ .Values.global.secrets.INTERNAL_API_KEY | quote }}
