replicaCount: 1

image:
  repository: auth-service
  tag: latest
  pullPolicy: IfNotPresent


container:
  port: 80

services:
  - type: ClusterIP
    port: 80

config:
  DATABASE_URL: ""
  DATABASE_PORT: ""
  DATABASE_NAME: ""
  DATABASE_SCHEMA: ""
  DATABASE_USERNAME: ""
  DATABASE_PASSWORD: ""
  JWT_SECRET_KEY: ""
  JWT_TOKEN_VALIDITY: ""
  INTERNAL_API_KEY: ""
  USER_SERVICE_URL: ""