postgresql:
  auth:
    username: myuser
    password: mypassword
    database: mydb

  service:
    type: ClusterIp 
    ports: 
      postgresql: 5432

  primary:
    initdb:
      scripts:
        create-schemas.sql: |
          CREATE SCHEMA IF NOT EXISTS auth_schema AUTHORIZATION myuser;
          CREATE SCHEMA IF NOT EXISTS user_schema AUTHORIZATION myuser;

auth-service:
  config:
    DATABASE_URL: local-postgresql
    DATABASE_PORT: "5432"
    DATABASE_NAME: mydb
    DATABASE_SCHEMA: auth_schema
    DATABASE_USERNAME: myuser
    DATABASE_PASSWORD: mypassword
    JWT_SECRET_KEY: bG9jYWwtc2VjcmV0
    JWT_TOKEN_VALIDITY: "3600"
    INTERNAL_API_KEY: local-api-key
    USER_SERVICE_URL: http://user-service:8080
