
# DEPENDECIES
# TODO capire come passare password e username
postgresql:
  auth:
    username: myuser
    password: mypassword
    database: mydb

  service:
    type: ClusterIp 
    ports: 
      postgresql: 5432

  primary:
    initdb:
      scripts:
        create-schemas.sql: |
          CREATE SCHEMA IF NOT EXISTS auth_schema AUTHORIZATION myuser;
          CREATE SCHEMA IF NOT EXISTS user_schema AUTHORIZATION myuser;
