postgresql:
  auth:
    username: myuser
    password: mypassword
    database: mydb

  service:
    type: ClusterIp 
    ports: 
      postgresql: 5432

  primary:
    initdb:
      scripts:
        create-schemas.sql: |
          CREATE SCHEMA IF NOT EXISTS auth_schema AUTHORIZATION myuser;
          CREATE SCHEMA IF NOT EXISTS user_schema AUTHORIZATION myuser;

global: 
  secrets:
    DATABASE_URL: local-postgresql
    DATABASE_PORT: "5432"
    DATABASE_NAME: mydb
    DATABASE_USERNAME: myuser
    DATABASE_PASSWORD: mypassword
    JWT_SECRET_KEY: u8L1Rj0yFz7vQpG3n5X9m2Kq7s4V8bW0Y1xA6hJ2fP0=
    JWT_TOKEN_VALIDITY: "360000"
    INTERNAL_API_KEY: local-api-key
    REGION: "eu-south-1"
    QUEUE_URL: ""
    AUTH_SERVICE_URL: http://local-auth-service-svc-0:8080
    USER_SERVICE_URL: http://local-user-service-svc-0:8081


auth-service:
  container:
    port: "8080"

    services:
      - type: ClusterIP
        port: "8080"
  config:
    SERVER_PORT: "8080"
    DATABASE_SCHEMA: auth_schema

user-service:
  container:
    port: "8081"

  services:
    - type: ClusterIP
      port: "8081"

  config:
    SERVER_PORT: "8081"
    DATABASE_SCHEMA: user_schema

api-gateway:
  container:
    port: "8082"

  services:
    - type: ClusterIP
      port: "8082"

  config: 
    SERVER_PORT: "8082"